name: Deploy to AWS Lambda

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      LAMBDA_S3_KEY: dmu-templates-service-0.0.1-SNAPSHOT-all.jar

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean shadowJar

      - name: Upload JAR to S3
        run: aws s3 cp build/libs/dmu-templates-service-0.0.1-SNAPSHOT-all.jar s3://microservices-lambda-archives/dmu-templates-service/dmu-templates-service-0.0.1-SNAPSHOT-all.jar

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve tfplan